apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      name: login-service
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: yeongho/login-service:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      